//! Generate the JavaScript fixture consumed by `docs/index.html`.
//!
//! This file is regenerated by `scripts/reproduce_paper.sh`; the HTML demo
//! verifies its JavaScript port against every case at page load.

use lotus::metrics::{UniformDomain, summarize_uniform_domain};
use lotus::{RECOMMENDED_PROFILES, lotus_encoded_bit_len};
use std::collections::BTreeSet;

fn fixture_values() -> Vec<u64> {
    let mut values = BTreeSet::new();
    for value in [0u64, 1, 2, 3, 5, 13, 42, 125, 126, 127, 128] {
        values.insert(value);
    }
    for width in 1..=64u32 {
        let start = (1u128 << width) - 2;
        let end = if width == 64 {
            u64::MAX as u128
        } else {
            (1u128 << (width + 1)) - 3
        };
        for candidate in [
            start.saturating_sub(1),
            start,
            start.saturating_add(1),
            end.saturating_sub(1),
            end,
        ] {
            if let Ok(value) = u64::try_from(candidate) {
                values.insert(value);
            }
        }
    }
    for group in 1..=9u32 {
        let boundary = 1u128 << (7 * group);
        for candidate in [
            boundary.saturating_sub(1),
            boundary,
            boundary.saturating_add(1),
        ] {
            if let Ok(value) = u64::try_from(candidate) {
                values.insert(value);
            }
        }
    }
    values.into_iter().collect()
}

fn main() {
    print!("window.LOTUS_REFERENCE={{\"format\":1,\"profiles\":[");
    for (index, profile) in RECOMMENDED_PROFILES.iter().enumerate() {
        if index != 0 {
            print!(",");
        }
        print!(
            "{{\"label\":\"{}\",\"j\":{},\"d\":{},\"max\":\"{}\"}}",
            profile.label,
            profile.config.jumpstarter_bits,
            profile.config.tiers,
            profile.config.max_u64_value().expect("valid profile")
        );
    }

    print!("],\"cases\":[");
    let mut first = true;
    for value in fixture_values() {
        for profile in RECOMMENDED_PROFILES {
            if !first {
                print!(",");
            }
            first = false;
            let bits = lotus_encoded_bit_len(
                value,
                profile.config.jumpstarter_bits,
                profile.config.tiers,
            );
            print!(
                "{{\"value\":\"{}\",\"label\":\"{}\",\"bits\":",
                value, profile.label
            );
            match bits {
                Ok(bits) => print!("{bits}"),
                Err(_) => print!("null"),
            }
            print!("}}");
        }
    }

    let u32_summary = summarize_uniform_domain(UniformDomain {
        name: "uniform_u32",
        start: 0,
        end: u32::MAX as u64,
    });
    print!("],\"uniformU32\":[");
    for (index, result) in u32_summary.lotus.iter().enumerate() {
        if index != 0 {
            print!(",");
        }
        print!("{{\"label\":\"{}\",\"totalBits\":", result.label);
        match result.total_bits {
            Some(total) => print!("\"{total}\""),
            None => print!("null"),
        }
        print!(",\"wins\":");
        match result.versus_leb128 {
            Some(counts) => print!("\"{}\"", counts.wins),
            None => print!("null"),
        }
        print!(",\"ties\":");
        match result.versus_leb128 {
            Some(counts) => print!("\"{}\"", counts.ties),
            None => print!("null"),
        }
        print!(",\"losses\":");
        match result.versus_leb128 {
            Some(counts) => print!("\"{}\"", counts.losses),
            None => print!("null"),
        }
        print!("}}");
    }
    println!(
        "],\"uniformU32Values\":\"{}\",\"uniformU32LebBits\":\"{}\"}};",
        u32_summary.values, u32_summary.leb128_total_bits
    );
}
